// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy3os7QY3lXTSztwn5ja1g2pZJRCXDF0A',
    appId: '1:852266961214:web:2d3d60ad8819be7e13046f',
    messagingSenderId: '852266961214',
    projectId: 'sales-notes',
    authDomain: 'sales-notes.firebaseapp.com',
    storageBucket: 'sales-notes.firebasestorage.app',
    measurementId: 'G-EL0J44Z8QX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpT0kX5aYl-2AyCIgs26sZ8MNM-PZkedM',
    appId: '1:852266961214:android:05bb355e337da9cd13046f',
    messagingSenderId: '852266961214',
    projectId: 'sales-notes',
    storageBucket: 'sales-notes.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6HzWANL4mSmR4kjmvLXl7bQOAr0WRdKo',
    appId: '1:852266961214:ios:7c06e5ac2879448d13046f',
    messagingSenderId: '852266961214',
    projectId: 'sales-notes',
    storageBucket: 'sales-notes.firebasestorage.app',
    androidClientId: '852266961214-31207a3bcdrjofvfqmvgfnqa8h3hcaad.apps.googleusercontent.com',
    iosClientId: '852266961214-50vgtfjrnjqqb0qvbv0276i9bj74te1t.apps.googleusercontent.com',
    iosBundleId: 'com.example.salesProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6HzWANL4mSmR4kjmvLXl7bQOAr0WRdKo',
    appId: '1:852266961214:ios:7c06e5ac2879448d13046f',
    messagingSenderId: '852266961214',
    projectId: 'sales-notes',
    storageBucket: 'sales-notes.firebasestorage.app',
    androidClientId: '852266961214-31207a3bcdrjofvfqmvgfnqa8h3hcaad.apps.googleusercontent.com',
    iosClientId: '852266961214-50vgtfjrnjqqb0qvbv0276i9bj74te1t.apps.googleusercontent.com',
    iosBundleId: 'com.example.salesProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy3os7QY3lXTSztwn5ja1g2pZJRCXDF0A',
    appId: '1:852266961214:web:fb3516b934a69f5313046f',
    messagingSenderId: '852266961214',
    projectId: 'sales-notes',
    authDomain: 'sales-notes.firebaseapp.com',
    storageBucket: 'sales-notes.firebasestorage.app',
    measurementId: 'G-GB9XQESSQJ',
  );

}